version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: samurai-postgres
    environment:
      POSTGRES_DB: mcpserver
      POSTGRES_USER: mcpuser
      POSTGRES_PASSWORD: mcppassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mcpuser -d mcpserver"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: